#存放待ping的ip 文件名称（默认为当前文件夹下ip.txt）.
ipFilename: ip.txt
#每个ip段选择的ip数量 如从111.111.111.X这个ip段中随机选择10个ip，该项必须，不能为0且小于等于255
selectCountEveryIp: 1
#ping测试最大协程数(默认100，数字越大越快，但可能影响结果准确性)
pingRoutine: 200
#每个ip ping次数(默认10)
pingCount: 10
#下载测试最大协程数(默认1，数字越大可能影响测试结果)
downloadRoutine: 3
#需下载测试的ip节点个数(默认10)
downloadTestCount: 1
#下载测试时间(默认10,单位为秒)
downloadSecond: 10
#测试资源url，该资源需缓存在cloudflare上
downloadUrl: https://storage.idx0.workers.dev/Images/public-notion-06b4a73f-0d4e-4b8f-b273-77becf84a0b3.png
#筛选ip 最大ping延迟限制（默认200，单位ms）
rttLimit: 200
#筛选ip 最小ping收包率限制（默认0，0<=该值<=100）
recvRateLimit: 90
#是否输出前5个ip数据到txt文件
isOutputTxt: false

#修改dnspod所需配置
dns:
  #是否需要修改dns，bool类型
  modifyEnable: true
  #筛选ip 最小速度限制（默认0，单位MB/s）
  speedLimit: 1.5
  #域名，必需项
  domain: example.com
  #dnspod令牌，必需项
  dnspodToken: 123456,bbcc6bb8cfec9c157e9e11bdd42cdc5b
  #主机记录, 如 www
  subDomain: www
  #记录ID，必需项
  recordId: 619385918
  #记录类型，比如：A，必需项
  recordType: A
  #记录线路，比如：默认，必需项
  recordLine: 电信